name: prototipo_funcional
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.1.1  # Mantén esta versión para dispositivos móviles
  google_maps_flutter_web: ^0.5.12  # Cambia a esta versión para la web


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/recycling_logo.png
    - assets/images/recycling_illustration.png
    - assets/images/profile_picture.png
    - assets/images/map_simulation.png
    - assets/images/andres_profile.png
    - assets/images/luz_profile.png
